# Required to run your project under the correct environment.
language: php
dist: trusty
sudo: false

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: nightly

# Commands to be run before your environment runs.
install:
  - composer install --dev --no-interaction --prefer-dist
  - phpenv rehash

script:
  - ./vendor/bin/grumphp run
